{
    users:{
        XXX(userId):{
            userId:(uid)
            username:
            photoURL:
            email:
            lineID:
            phone:
            nickname:
            gender:
            age:
            description:
            profession:
            interests:
            faceScore:
            
        }
        ...
    }
    user-activities:{
        XXX(userId):{
                activityId:
                date:
                gender:
                confirmDate:
                movie:
                availabeTime:
                location:
                status:0:按下報名,1:無匯款，取消場次,2:配對中,3:已錄取，接收簡訊,4:無錄取，配對失敗,5:退款中,6:活動結束
                accountLastFive:          
        },{

        }
        ...
    }
    activity-users:{
        YYY(activityID):{
             XXX(userID){
            userID: XXX(userID),
            status:0:按下報名,1:無匯款，取消場次,2:配對中,3:已錄取，接收簡訊,4:無錄取，配對失敗,5:退款中,6:活動結束,
            location:
            gender:
        }...
    }...

    activitiesUserSignUp:{
           YYY(activityId):{
                    activityID:
                    index:
                    name:
                    subject:
                    date:
                    movie:
                    location:
                    status://0:不能報名,1:可以報名,2:結束了（不會顯示）
            }
    }
    activities:{
          YYY(activityId):{
                    activityID:
                    index:
                    name:
                    subject:
                    date:
                    movie:
                    location:
                    users:[userId,userId...]
                    status://0:不能報名,1:可以報名,2:結束了（不會顯示）
                }
        ...
        }
        ...
    }
    activitiesGroup:{
        Taipei(location):{
            YYY(activityId):{
                ZZZ(lineGroupId):{
                    boy:{
                        userId:
                        username:
                        photourl:
                        phone:
                        lineId:
                        age:
                    },
                    girl:{
                        userId
                        username:
                        photourl:
                        phone:
                        lineId:
                        age:
                    }
                    date:
                    commonMovie:
                    status-group://0:在群組中，還未約定時間,1:已約好時間,2:當天約會,3:約會完成
                }
                ...
            }
            ...
        }
        ...
    }
}